Калькулятор
js-tasks-ru/jsbasic-20230727_crusade7 pull request #9
Opened 2023-09-06 19:19 UTC by tonserbin

2023-09-06 19:20 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-09-07 05:19 UTC, koalex requested changes
Добавлена задача **3-1**, но не решена. Без решения **3-1** не смогу принять ПР

2023-09-07 06:49 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2023-09-07 15:38 UTC, koalex approved these changes

2023-09-07 15:38 UTC, merged